### ISSUE TITLE
The "cloudflared" gets error while in a different  package name

### ISSUE THREAD

**Issue by nbsn** [animegasan/luci-app-cloudflared#1]
In this example, the "cloudflared" package named "openwrt-cloudflared" did not work. Hope you can fix it. Thanks.

[root@OpenWrt:02:17 PM /tmp] # opkg list | grep cloudfl
ddns-scripts-cloudflare - 2.8.2-35 - Dynamic DNS Client scripts extension for cloudflare.com API v4 (require curl)
ddns-scripts-cloudflare - 2.8.2-37 - Dynamic DNS Client scripts extension for cloudflare.com API v4 (require curl)
luci-app-cloudflarespeedtest - git-24.217.56735-8015371 - LuCI support for Cloudflares Speed Test
openwrt-cloudflared - 2023.8.2-46 - Argo tunnel client
[root@OpenWrt:02:17 PM /tmp] # 
[root@OpenWrt:02:17 PM /tmp] # 
[root@OpenWrt:02:17 PM /tmp] # opkg install luci-app-cloudflared_1.0.1-20232507_all.ipk
Installing luci-app-cloudflared (1.0.1-20232507) to root...
Collected errors:
 *pkg_hash_check_unresolved: cannot find dependency cloudflared for luci-app-cloudflared
 *satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-cloudflared:
 *cloudflared
 *opkg_install_cmd: Cannot install package luci-app-cloudflared.
[root@OpenWrt:02:18 PM /tmp] #

**Comment by animegasan** [comment]
Installing on what version of OpenWRT?

**Comment by animegasan** [comment]
This package cannot use this IPK because the settings are different. I recommend using the cloudflared package instead.

I think the problem has been resolved. Thanks
